[package]
name = "lang"
version = "0.1.0"
authors = ["hadxu <hadxu@tencent.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "8.2.0"

[[bin]]
name = "wasm"
path = "src/wasm/main.rs"

